version: '3.8'
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    networks:
      - node-network

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - '5173:5173'

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge
