services:
  backend:
    image: gigih-assessment/backend
    build:
      context: backend
      dockerfile: ./backend/Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    networks:
      - node-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge
